apiVersion: v1
kind: Service
metadata:
  name: mern-stack-front-to-back-service
spec:
  selector:
    app: mern-stack-front-to-back
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-stack-front-to-back-deployment
  labels:
    app: mern-stack-front-to-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-stack-front-to-back
  template:
    metadata:
      labels:
        app: mern-stack-front-to-back
    spec:
      containers:
      - name: mern-stack-front-to-back
        image: "docker-registry.k8s.lan:30501/com.opcode.mern-stack-front-to-back:{{image_version}}"
        ports:
        - name: rest-api
          containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mern-stack-front-to-back-secret
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mern-stack-front-to-back-secret
              key: JWT_SECRET
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mern-stack-front-to-back-secret
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mern-stack-front-to-back-secret
              key: GITHUB_CLIENT_SECRET
